Traceback (most recent call last):
  File "/u/antor/u12/alochab/cs578/Lottery-Ticket-Hypothesis-in-Pytorch/LTH.py", line 332, in <module>
    main(args, ITE=1)
  File "/u/antor/u12/alochab/cs578/Lottery-Ticket-Hypothesis-in-Pytorch/LTH.py", line 60, in main
    model = fc1.fc1().to(device)
NameError: name 'fc1' is not defined
Traceback (most recent call last):
  File "/u/antor/u12/alochab/cs578/Lottery-Ticket-Hypothesis-in-Pytorch/LTH.py", line 332, in <module>
    main(args, ITE=1)
  File "/u/antor/u12/alochab/cs578/Lottery-Ticket-Hypothesis-in-Pytorch/LTH.py", line 60, in main
    model = fc1.fc1().to(device)
NameError: name 'fc1' is not defined
